'''
Created on 22-jul-2011

@author: Kevin Van Wilder <kevin@tick.ee>
'''

ACCESS_TOKEN_LENGTH = 10
REFRESH_TOKEN_LENGTH = 10
CLIENT_KEY_LENGTH = 30
CLIENT_SECRET_LENGTH = 20 
ALLOWED_CHARACTERS = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ0123456789'