'''
Created on 22-jul-2011

@author: kevin
'''

ACCESS_TOKEN_LENGTH = 10
REFRESH_TOKEN_LENGTH = 10
CLIENT_KEY_LENGTH = 30
CLIENT_SECRET_LENGTH = 20 
ALLOWED_CHARACTERS = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789_/*-+.!@#?[]%&'